ES 5.0 support
vkhatri/chef-elasticsearch-cluster pull request #77
Opened 2016-10-29 05:10 UTC by WeiBanjo

- Added config_v5 attributes for v5 configuration
- Added `jvm_options_file` config file for JVM configuration
- Removed JVM environment sysconfig for v5 due to [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking_50_packaging.html)
- Spec tests

2016-10-31 04:47 UTC, shortdudey123 requested changes

2016-10-31 04:47 UTC, shortdudey123 commented on recipes/config.rb
> +raise "require value for node['elasticsearch']['config']['cluster.name']" unless node['elasticsearch'][node['elasticsearch']['config_attribute']]['cluster.name']
use variable in raise string as well

2016-10-31 04:47 UTC, shortdudey123 commented on spec/unit/recipes/default_spec.rb
> +        node.normal['elasticsearch']['config']['cluster.name'] = 'spec'
`default` is preferred over `normal`

2016-10-31 04:47 UTC, shortdudey123 commented on attributes/config_v5.rb
> +# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
use `5.0` in doc links instead of `current` so that the correct version of the doc is always referenced and not just latest

2016-10-31 06:41 UTC, shortdudey123 commented
Closes https://github.com/vkhatri/chef-elasticsearch-cluster/issues/76

2016-11-02 01:21 UTC, vkhatri commented
Will merge it later today. Thanks @WeiBanjo @shortdudey123

2016-11-02 02:27 UTC, shortdudey123 commented
@vkhatri should probably look at https://github.com/vkhatri/chef-elasticsearch-cluster/pull/78 first
Then this PR can be rebased on master to verify that tests pass

2016-11-13 00:22 UTC, merged

2016-11-13 05:59 UTC, vkhatri commented
@WeiBanjo @shortdudey123 👍